name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create or Update Release and Upload Files
        uses: softprops/action-gh-release@v2
        with:
          # Change 'tag_name' to a new version (e.g., v1.0.1) to create a new release.
          # If you keep the same tag (e.g., 'latest'), it will update the existing release.
          tag_name: v.1.2.1
          # Change 'name' to match your release version if you update 'tag_name'.
          name: Coolfolio v1.2.1
          # Update 'body' with release notes or version info as needed.
          body: "Automated release from main branch."
          draft: false
          prerelease: false
          # This uploads all files in the repository to the release.
          files: ./**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}