name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version in version.txt
        run: echo "${{ github.ref_name }}" > version.txt

      - name: Commit version.txt to main branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "Update version.txt to ${{ github.ref_name }}" || echo "No changes to commit"
          git push origin HEAD:main

      - name: Create or Update Release and Upload Files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v.1.2.3
          name: Coolfolio v1.2.3
          body: "Automated release from main branch."
          draft: false
          prerelease: false
          files: ./**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}