name: Publish Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3



      - name: Create or Update Release and Upload Files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v.1.2.4
          name: Coolfolio v1.2.4
          body: "Automated release from main branch."
          draft: false
          prerelease: false
          files: ./**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}